/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoucherIndexRouteImport } from './routes/voucher.index'
import { Route as VoucherCodeRouteImport } from './routes/voucher.$code'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as UsernameConteudosRouteImport } from './routes/$username.conteudos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherIndexRoute = VoucherIndexRouteImport.update({
  id: '/voucher/',
  path: '/voucher/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoucherCodeRoute = VoucherCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => VoucherRoute,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UsernameConteudosRoute = UsernameConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => UsernameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/conteudos': typeof ConteudosRoute
  '/login': typeof LoginRoute
  '/$username/conteudos': typeof UsernameConteudosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/voucher/$code': typeof VoucherCodeRoute
  '/voucher/': typeof VoucherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/conteudos': typeof ConteudosRoute
  '/login': typeof LoginRoute
  '/$username/conteudos': typeof UsernameConteudosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/superadmin': typeof AuthenticatedSuperadminRoute
  '/voucher/$code': typeof VoucherCodeRoute
  '/voucher': typeof VoucherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/conteudos': typeof ConteudosRoute
  '/login': typeof LoginRoute
  '/$username/conteudos': typeof UsernameConteudosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRoute
  '/voucher/$code': typeof VoucherCodeRoute
  '/voucher/': typeof VoucherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/conteudos'
    | '/login'
    | '/$username/conteudos'
    | '/admin'
    | '/superadmin'
    | '/voucher/$code'
    | '/voucher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/conteudos'
    | '/login'
    | '/$username/conteudos'
    | '/admin'
    | '/superadmin'
    | '/voucher/$code'
    | '/voucher'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/_authenticated'
    | '/conteudos'
    | '/login'
    | '/$username/conteudos'
    | '/_authenticated/admin'
    | '/_authenticated/superadmin'
    | '/voucher/$code'
    | '/voucher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConteudosRoute: typeof ConteudosRoute
  LoginRoute: typeof LoginRoute
  VoucherIndexRoute: typeof VoucherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher/': {
      id: '/voucher/'
      path: '/voucher'
      fullPath: '/voucher/'
      preLoaderRoute: typeof VoucherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voucher/$code': {
      id: '/voucher/$code'
      path: '/$code'
      fullPath: '/voucher/$code'
      preLoaderRoute: typeof VoucherCodeRouteImport
      parentRoute: typeof VoucherRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/$username/conteudos': {
      id: '/$username/conteudos'
      path: '/conteudos'
      fullPath: '/$username/conteudos'
      preLoaderRoute: typeof UsernameConteudosRouteImport
      parentRoute: typeof UsernameRoute
    }
  }
}

interface UsernameRouteChildren {
  UsernameConteudosRoute: typeof UsernameConteudosRoute
}

const UsernameRouteChildren: UsernameRouteChildren = {
  UsernameConteudosRoute: UsernameConteudosRoute,
}

const UsernameRouteWithChildren = UsernameRoute._addFileChildren(
  UsernameRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConteudosRoute: ConteudosRoute,
  LoginRoute: LoginRoute,
  VoucherIndexRoute: VoucherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
